version: '3.3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 1111

  flask:
    build: ./flask_app  # Path to your Flask app directory
    ports:
      - "3001:8000"  # แก้ไขพอร์ตให้ตรงกันกับ Dockerfile
    depends_on:
      - db
    environment:
      FLASK_ENV: development
      FLASK_APP: main:app
      DATABASE_URL: mysql+mysqlconnector://root:1111@db/db

volumes:
  db_data:
