version: '3.3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql  # กำหนด volume เพื่อเก็บข้อมูล

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 1111  # เปลี่ยนรหัสผ่านให้ตรงกัน

  flask:
    build: ./flask_app  # Path to your Flask app directory
    ports:
      - "3001:5000"  # แก้ไขพอร์ตให้ตรงกับที่ Flask ใช้
    depends_on:
      - db
      
volumes:
  db_data:  # กำหนด volume ที่จะใช้เก็บข้อมูลของฐานข้อมูล
