version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: 1111
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: userpassword

  flask:
    build: ./flask_app  # Path to your Flask app directory
    ports:
      - "3001:5000"
    depends_on:
      - db
